# Generated by Django 4.1.2 on 2022-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='No name', max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=256, verbose_name='Почта')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('blocked', 'Заблокировано')], default='active', max_length=100, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
